<section>
    <h3>listagem</h3>
    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Idade</th>
            </tr>
        </thead>
        <tbody>
             {content} 
        </tbody>
    </table>
</section>